# Generated by Django 5.2.13 on 2026-04-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('aadhar', models.BigIntegerField(unique=True)),
                ('address', models.CharField(max_length=256)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=50)),
                ('pin', models.CharField(default='0', max_length=200)),
                ('balance', models.FloatField(default=1000)),
            ],
        ),
    ]
